"use client";
import { ParallaxScrollSecond } from "./ui/parallax-scroll";
import Section from "./Section";

export function ParallaxScrollSecondDemo() {
  return <Section id="demo">
  <ParallaxScrollSecond images={images} />;
  </Section>
}

const images = [
  "src/assets/bride/1.jpg",
  // "src/assets/bride/2.jpg",
  "src/assets/bride/3.jpg",
  "src/assets/bride/4.jpg",
  "src/assets/bride/5.jpg",
  "src/assets/bride/6.jpg",
  "src/assets/bride/7.jpg",
  // "src/assets/bride/8.jpg",
  // "src/assets/bride/9.jpg",
  "src/assets/bride/10.jpg",
  "src/assets/bride/11.jpg",
  "src/assets/bride/12.jpg",
  // "src/assets/bride/13.jpg",
  // "src/assets/bride/14.jpg",
  "src/assets/bride/15.jpg",
  // "src/assets/bride/16.jpg",
  "src/assets/bride/17.jpg",
  "src/assets/bride/18.jpg",
  "src/assets/bride/19.jpg",
  "src/assets/bride/20.jpg",
  // "src/assets/bride/21.jpg",
  "src/assets/bride/22.jpg",
  "src/assets/bride/23.jpg",
  // "src/assets/bride/24.jpg",
  // "src/assets/bride/25.jpg",
  // "src/assets/bride/26.jpg",
  "src/assets/bride/27.jpg",
  "src/assets/bride/28.png",
  "src/assets/bride/29.jpg",
  "src/assets/bride/30.jpg",
  "src/assets/bride/31.jpg",
  // "src/assets/bride/32.jpg",
  // "src/assets/bride/33.jpg",
  "src/assets/bride/34.jpg",
  "src/assets/engagement/01.jpg",
  "src/assets/engagement/02.jpg",
  "src/assets/engagement/03.jpg",
  "src/assets/engagement/05.jpg",
  "src/assets/engagement/06.jpg",
  "src/assets/engagement/09.jpg",
  "src/assets/engagement/11.jpg",
  "src/assets/engagement/14.jpg",
  "src/assets/engagement/15.jpg",

  "src/assets/groom/1.jpg",
  "src/assets/groom/2.jpg",
  "src/assets/groom/413D1982-3F44-4008-8871-A7F507E7B360.jpg",
  "src/assets/groom/9095D490-112B-4847-8291-2C5C453D1B14.JPEG",
  "src/assets/groom/IMG_9461.JPG",
  "src/assets/groom/IMG_9462.JPG",
  "src/assets/groom/IMG_9464.JPG",
  "src/assets/groom/IMG_9465.JPG",
  "src/assets/groom/IMG_9560.JPG",
  "src/assets/groom/IMG_9561.JPG",
  "src/assets/groom/IMG_9562.JPG",
  "src/assets/groom/IMG_9563.JPG",
  "src/assets/groom/IMG_9564.JPG",
  "src/assets/groom/IMG_9983.JPG",
  "src/assets/groom/IMG_9984.JPG",
  "src/assets/groom/IMG_9986.JPG",

  "src/assets/prewedding/1.JPEG",
  "src/assets/prewedding/2.JPEG",
  "src/assets/prewedding/3.JPEG",
  "src/assets/prewedding/4.JPEG",
  "src/assets/prewedding/5.JPEG",
  "src/assets/prewedding/6.JPEG",
  "src/assets/prewedding/7.JPEG",
  "src/assets/prewedding/8.JPEG",
  "src/assets/prewedding/9.JPEG",
  "src/assets/prewedding/10.JPEG",
  "src/assets/prewedding/11.JPEG",
  "src/assets/prewedding/12.JPEG",
  "src/assets/prewedding/13.JPEG",
  "src/assets/prewedding/14.JPEG",
  "src/assets/prewedding/15.JPEG",
  "src/assets/prewedding/16.JPEG",
  "src/assets/prewedding/17.JPEG",
  "src/assets/prewedding/18.JPEG",
  "src/assets/prewedding/19.JPEG",
  "src/assets/prewedding/20.JPEG",
  "src/assets/prewedding/21.JPEG",
  "src/assets/prewedding/22.JPEG",
  "src/assets/prewedding/23.JPEG",
  "src/assets/prewedding/24.JPEG",
  "src/assets/prewedding/25.JPEG",
  "src/assets/prewedding/26.JPEG",
  "src/assets/prewedding/27.JPEG",
  "src/assets/prewedding/28.JPEG",
  "src/assets/prewedding/29.JPEG",
  "src/assets/prewedding/30.JPEG",
  "src/assets/prewedding/31.JPG",
  "src/assets/prewedding/32.JPEG",
  "src/assets/prewedding/33.JPEG",
  "src/assets/prewedding/34.JPEG",
  "src/assets/prewedding/35.JPEG",
  "src/assets/prewedding/36.JPEG",
  "src/assets/prewedding/37.JPEG",
  "src/assets/prewedding/38.JPEG",
  "src/assets/prewedding/39.JPEG",
  "src/assets/prewedding/40.JPEG",
  "src/assets/prewedding/41.JPEG",
 
];
